export const CHANGE_SEARCH_FIELD = 'CHANGE_SEARCH_FIELD';

export const REQUEST_BURGERS_PENDING = 'REQUEST_BURGERS_PENDING';
export const REQUEST_BURGERS_SUCCESS = 'REQUEST_BURGERS_SUCCESS';
export const REQUEST_BURGERS_FAILED = 'REQUEST_BURGERS_FAILED';